### ISSUE TITLE
[Feature Request] Option to reschedule card after review

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#194] opened 2023-08-19 13:10 UTC
I have seen comments from many users that they don't want to reschedule all their cards while switching to FSRS from SM-2 because it results in a huge backlog.
Examples:
- https://www.reddit.com/r/Anki/comments/15rmp13/comment/jwa92er
- https://www.reddit.com/r/Anki/comments/15rmp13/comment/jwlc1nb

The current suggestion for them is to either not reschedule at all (and allow the FSRS scheduler to do all the work) or to use the "reschedule cards reviewed in last x days" option every day.

A better solution would be to add an option that reschedules the card as soon as it is reviewed. This would be quite similar to how the "disperse siblings after review" feature currently works.
For better results, this new feature should be executed before the disperse siblings feature so that the dispersal of the siblings is not reversed.

**Comment by Expertium** [comment] 2023-08-20 09:51
I think we've talked about something similar in the past, and I don't remember why this wasn't implemented. But yes, it would be a good feature for a more slow and seamless transition from Anki's algorithm to FSRS.

**Comment by L-M-Sherlock** [comment] 2023-08-22 07:59
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12406380/fsrs4anki-helper.zip)
Have a try.

**Comment by Expertium** [comment] 2023-08-22 08:54
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/ea5975be-c15a-42d0-ae3f-18086f3db7d1)
I don't see any changes.

**Comment by L-M-Sherlock** [comment] 2023-08-22 09:14
I haven't added the config. But it has worked in all reviews.

**Comment by L-M-Sherlock** [comment] 2023-08-22 09:30
Do you need me to add tooltip to inform you that the card has been rescheduled after review?

**Comment by Expertium** [comment] 2023-08-22 09:33
I think that it should become a new option, like "Auto reschedule the card after review". The issue is that users will ask "Wait, but then why do we even need the scheduler if the helper add-on is doing this?".

**Comment by L-M-Sherlock** [comment] 2023-08-22 09:57
Oh, the patch has a bug. Here is the fixed version with tooltip (for test).
[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12407481/fsrs4anki-helper.zip)


> I think that it should become a new option, like "Auto reschedule the card after review". The issue is that users will ask "Wait, but then why do we even need the scheduler if the helper add-on is doing this?".

Yeah. So how to explain it to the user?

**Comment by Expertium** [comment] 2023-08-22 10:11
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/c5e13047-af92-42ea-b1ce-3cb75cf7f5f0)
Should I copy-paste the contents of fsrs4anki-helper.zip into the folder after deleting all other files in thar folder (aka a "clean" reinstall)? Usually I just copy-paste new files into the folder with replacement, without deleting all other files

**Comment by L-M-Sherlock** [comment] 2023-08-22 10:12
You can rename fsrs4anki-helper.zip to fsrs4anki-helper.ankiaddon and click it to install.

**Comment by Expertium** [comment] 2023-08-22 10:15
I get a different error now
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.64 (581f82c5) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-08-21 13:48:14

Caught exception:
Traceback (most recent call last):
  File "aqt.errors", line 207, in onTimeout
  File "aqt.progress", line 246, in clear
  File "aqt.progress", line 230, in finish
  File "aqt.progress", line 274, in _closeWin
TypeError: isdeleted() argument 1 must be PyQt6.sip.simplewrapper, not None
```

**Comment by Expertium** [comment] 2023-08-22 10:16
Nevermind, not the same
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.64 (581f82c5) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-08-21 13:48:14

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 125, in wrapped_done
  File "aqt.reviewer", line 460, in after_answer
  File "aqt.reviewer", line 473, in _after_answering
  File "_aqt.hooks", line 3910, in __call__
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 386, in reschedule_when_review
    mw.col.merge_undo_entries(undo_entry)
  File "anki.collection", line 1054, in merge_undo_entries
  File "anki._backend_generated", line 1823, in merge_undo_entries
  File "anki._backend", line 156, in _run_command
anki.errors.InvalidInput: target undo op not found
```

**Comment by L-M-Sherlock** [comment] 2023-08-22 10:24
Oops. It is caused by undo module. I need some time to read the source code.

**Comment by L-M-Sherlock** [comment] 2023-08-22 10:36
Oh, I can't merge `reschedule_when_review` and `disperse_siblings_when_review` into `Answer Card` of Anki when they are separated.

**Comment by L-M-Sherlock** [comment] 2023-08-22 10:45
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12407926/fsrs4anki-helper.zip)

Fixed. Please test it again.

**Comment by Expertium** [comment] 2023-08-22 11:03
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/2d28fe10-2844-465f-b705-ba577bc6dfd9)
It seems like the intervals afetr rescheduling are longer, I don't know why.

**Comment by L-M-Sherlock** [comment] 2023-08-22 11:35
> It seems like the intervals after rescheduling are longer, I don't know why.

Because the rescheduling applies load balance here.

**Comment by Expertium** [comment] 2023-08-22 12:07
@user1823 you should test this too, before Sherlock pushes this new update. Also, what's your opinion on this:


> > I think that it should become a new option, like "Auto reschedule the card after review". The issue is that users will ask "Wait, but then why do we even need the scheduler if the helper add-on is doing this?".
> 
> Yeah. So how to explain it to the user?

**Comment by Expertium** [comment] 2023-08-22 14:13
It happens with cards from any deck
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/46ebc834-ed05-467a-9d56-3e7a1930dc5a)

**Comment by L-M-Sherlock** [comment] 2023-08-22 14:21
That card is still in relearning stage. So the interval is the card's last interval.

**Comment by Expertium** [comment] 2023-08-22 14:27
Just to be clear, it happens regardless of whether the card was in "review" stage or in "learning" stage when I pressed "Again".

**Comment by user1823** [comment] 2023-08-22 16:30
The implementation seems to be working well. But, I have a few points to share:
- The feature should not be enabled by default. It should be behind a config option.
- Because this feature is currently default, it seems that you have disabled disperse_siblings_when_review. So, please re-enable this.
<img width="932" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/604f80dd-2b56-4955-96ee-271b1f87c0b5">

- The tooltips should not be shown (though I think that you are showing them currently for the purpose of review).

> The issue is that users will ask "Wait, but then why do we even need the scheduler if the helper add-on is doing this?".

Unfortunately, I don't have any good answer to this.

**Comment by user1823** [comment] 2023-08-22 17:19
In some cases, I noticed that there was a slight difference in the stability before and after rescheduling.

```
cid = 1668528677033
s before = 67.64
s after = 67.65
```

```
cid = 1655996883494
s before = 91.53
s after = 91.52
```

I do realise that these are pretty small differences. But ideally, there should be no difference at all.

**Comment by Expertium** [comment] 2023-08-22 17:35
> * The feature should not be enabled by default. It should be behind a config option.

Why?

**Comment by L-M-Sherlock** [comment] 2023-08-23 02:04
> In some cases, I noticed that there was a slight difference in the stability before and after rescheduling.

Because the custom data has precision limitation. I can't store a too long string of stability in custom data.

**Comment by L-M-Sherlock** [comment] 2023-08-23 02:07
> * Because this feature is currently default, it seems that you have disabled disperse_siblings_when_review. So, please re-enable this.

I didn't disable it. Please see this code:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/5634daf43535015342e8b474e9f0bcc34ebfdf30/schedule/__init__.py#L7-L9

This code ensures the `reschedule_when_review` is applied before `disperse_siblings_when_review`.

**Comment by L-M-Sherlock** [comment] 2023-08-23 02:27
I removed the tooltip and added configuration for reschedule the card after review.

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12414526/fsrs4anki-helper.zip)

**Comment by Expertium** [comment] 2023-08-23 09:39
Seems to we working fine. @user1823 you should test this too.
We still need to decide how to explain this to users. Also, I think it should be enabled by default.

**Comment by L-M-Sherlock** [comment] 2023-08-23 09:48
We should introduce the Pros and Cons for this feature. Here is my opinion:

Pros:
1. You don't need to reschedule all cards at once, which could induce backlog.
2. The interval is more accurate for old cards with many reviews than using only the scheduler without rescheduling.
3. Load balance and free days are applied in rescheduling.

Cons:
1. The interval above rating buttons will be inconsistent with the real interval after rescheduling for those old cards.

You can supplement more.

**Comment by Expertium** [comment] 2023-08-23 09:50
You could put that in the FAQ or somewhere else, but the problem is that not many people read the wiki.

**Comment by Expertium** [comment] 2023-08-23 11:19
> Also, I think it should be enabled by default.

Actually, now that I think about it, both situations suck.
If it's enabled by default, users may notice that the intervals theur are seeing above the buttons are inconcsistent with real intervals. If it's disabled by default, the intervals won't be accurate.
I know how to solve this, but it may not be possible with the current implementation. The helper could go through the card's entire history and calculate accurate DSR values **before** the user has pressed "Show Answer".

**Closed** 2023-08-23 12:44 UTC
Labels: enhancement

**Comment by Vitorvlv** [comment] 2023-08-24 12:12
Just to make sure I understood it correctly, the only con against having this enabled is that the interval showed in anki UI and the one that actually gets applied are different right?

Otherwise this should be safe for daily use? 

Usually I've been doing a daily "reschedule cards reviewed in the last 7 days", this shouldn't be needed anymore, right?


How do I know it's actually doing something?

**Comment by Expertium** [comment] 2023-08-25 17:32
@Vitorvlv the other pro that Sherlock didn't mention is that with this new feature enabled, you can set learning steps logner than 1d. The only con is that the intervals displayed in Anki after you press "Show Answer" won't match reality, yes.
