### ISSUE TITLE
[Feature Request] Reducing amount of cards one needs to study on certain days

### ISSUE THREAD

**Issue by C-Nover** [open-spaced-repetition/fsrs4anki-helper#222] opened 2023-09-09 09:25 UTC
Ability to decrease the number of cards on specific occasions, like Sundays or particular dates.

**Comment by cjdduarte** [comment] 2023-09-24 13:29
Hello @L-M-Sherlock ,

I was in the process of starting the planned code modifications when I became aware of the release of Anki 23.10 beta. I have a question regarding this: How will the Helper add-on be integrated with this new version? Do you have any insights or official updates on this matter?

**Comment by cjdduarte** [comment] 2023-09-24 13:33
To clarify, my question arises due to the native integration of FSRS with Anki. Understanding how the Helper add-on aligns with this integration is crucial for the modifications.

**Comment by L-M-Sherlock** [comment] 2023-09-24 13:36
In long-term, the add-on will be integrated into Anki.

**Comment by L-M-Sherlock** [comment] 2023-09-24 13:37
But if this feature becomes too complex, I prefer to keep it in add-on.

**Comment by Expertium** [comment] 2023-11-06 17:36
@L-M-Sherlock me and Anking think that this would be a cool feature, so hopefully you will come back to this issue in the future

**Comment by L-M-Sherlock** [comment] 2023-11-15 04:30
@cjdduarte, the refactor has been done. Do you have any progress?

**Comment by Expertium** [comment] 2024-02-06 08:56
> Its problem is it's based on randomness. So it couldn't obey the X% perfectly.

Yeah, that doesn't seem ideal.

**Comment by user1823** [comment] 2024-02-06 08:59
The question is how perfectly. If it is within a 10% range (relative) around the desired percent, it looks good enough to me.

**Comment by L-M-Sherlock** [comment] 2024-02-06 09:45
Sorry I made a mistake. If the rescheduler only respect easy days in X% cases, it will reschedule cards in easy days in 1-X% because these days' reviews is the minimum. The good news is, I can calculate the Y% of probability based on X% easy degree and the number of easy days. The equation is:  

$$\cfrac{\frac{1-Y\\%}{N}}{\frac{Y\\%}{7-N}} = X\\%$$

For example, if the X% = 33% and the number of easy days is 2, the Y% should be equal to 88%.

Before:

<img width="700" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/16e0136b-733b-4092-8601-91a511260568">

After:

<img width="700" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/565f5d28-b3b0-4569-ad08-e80d3cee1c10">

**Comment by user1823** [comment] 2024-02-06 09:54
The second image looks good but I am not sure what does the first image represent.

I have one question:
In X%, what does 100% represent? Is it the workload on the rest of the days or is it the workload on the Easy day before applying reschedule?

If it is the latter case, then there is one problem. If the user reschedules the cards every day (using the Auto apply easy days option), the workload on the Easy days would continue to decrease. That is not expected.

**Comment by L-M-Sherlock** [comment] 2024-02-06 10:11
> In X%, what does 100% represent?

Sorry for the confusing symbols/names. X means the workload of easy days divided by the workload of non-easy days. If X = 0%, the workload of easy days will near to 0% of the non-easy days (the current implementation).

**Comment by L-M-Sherlock** [comment] 2024-02-06 10:19
How about `easy_days_review_ratio`?

**Comment by user1823** [comment] 2024-02-06 10:22
I was about to suggest "Easy Days Review Percentage".

Both are OK. But, because it is a percentage, it suggest using "Easy Days Review Percentage".

**Comment by L-M-Sherlock** [comment] 2024-02-06 10:24
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/14178135/fsrs4anki-helper.ankiaddon.zip)

I haven't developed a GUI setting method for that. So you need to set it in the config directly.

<img width="631" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/a6578aa2-8237-4004-98d2-f6f5b8d4ba3f">

**Comment by Expertium** [comment] 2024-02-06 10:25
I believe that the original intention was to have different ratios for different days of the week.

**Comment by user1823** [comment] 2024-02-06 10:27
> the original intention 

It was not the original intention. It was suggested by another user/developer. But, it is harder to develop. Why not start with a simple feature first?

**Comment by user1823** [comment] 2024-02-06 11:20
Doesn't work well. I set the percent to 40 and this is what I got:
<img width="434" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/c36a1b26-4c1f-4f8c-99e0-e4a9e0179e84">

Also, this feature, by design, doesn't work for Easy days on specific days. Can you implement this too?

**Comment by L-M-Sherlock** [comment] 2024-02-06 11:53
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/14179039/fsrs4anki-helper.ankiaddon.zip)

I write an ugly but practical GUI to set the percentage:

<img width="294" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/ca3865b8-97b1-472c-98fc-08b7d0016214">

<img width="324" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/382e4e0c-ad9b-4598-a664-f368399a810a">

**Comment by L-M-Sherlock** [comment] 2024-02-06 11:57
> Doesn't work well. I set the percent to 40 and this is what I got:

I guess it's due to the fuzz range. Could you set a lower value and test it again?

> Also, this feature, by design, doesn't work for Easy days on specific days. Can you implement this too?

I'm afraid it doesn't work because the equation is based on the length of a week and the number of easy days. For Easy days on specific days, we need a completely different method.

**Comment by L-M-Sherlock** [comment] 2024-02-06 12:21
Do you use the `rescheduling all cards`?

**Comment by user1823** [comment] 2024-02-06 12:27
I was using "Apply Easy Days now" earlier. Rescheduling all cards solved the issue.

**Comment by L-M-Sherlock** [comment] 2024-02-06 12:53
If you accept that, I will merge the PR.

**Closed** 2024-02-07 01:35 UTC
Labels: enhancement, help wanted
