### ISSUE TITLE
Disperse Siblings freezing Anki

### ISSUE THREAD

**Issue by wagewarsgetrichdiegoncharov** [open-spaced-repetition/fsrs4anki-helper#111] opened 2023-06-01 14:15 UTC
I have tried to Disperse Siblings several times, and each time it runs indefinitely and appears to freeze my Anki app. This happens even when the number of sibling cards being dispersed is small.

<img width="509" alt="Screen Shot 2023-06-01 at 10 10 15 AM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/119229686/f822b8ac-46b8-4cd9-96c1-e424544e8d56">

My collection is large (65,000 cards) and some notes have 100+ cards, which I realize may be the issue. If there's any other documentation I should provide, please let me know!

**Comment by L-M-Sherlock** [comment] 2023-06-02 01:57
> My collection is large (65,000 cards) and some notes have 100+ cards

Oh, your case is a little tricky. The mechanism of `Disperse Siblings` is to combine all due range of siblings and to find the combination maximizing the due gap of each sibling. If the note has too many cards, its time complexity will increase exponentially.

**Comment by wagewarsgetrichdiegoncharov** [comment] 2023-06-02 02:29
Oof, makes sense! I wonder if that's something other users will run into.
But I understand that I've built my decks in a specific weird way so if
some add ons don't work for me, I get it.

**Comment by L-M-Sherlock** [comment] 2023-06-02 02:57
My plan is to filter out these notes. It will partially alleviate your problem.

**Comment by L-M-Sherlock** [comment] 2023-06-04 09:19
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11645250/fsrs4anki-helper.zip)

I develop a patch to solve your case. Could you help me test it?

**Comment by wagewarsgetrichdiegoncharov** [comment] 2023-06-04 16:18
That works! It took maybe 20 seconds to run on my very large, 165k card deck, but Anki didn't freeze. If there's any debugging or log info that's helpful for you, I'm happy to send it, you'll just have to tell me how. Thanks!

**Comment by user1823** [comment] 2023-06-04 16:39
@wagewarsgetrichdiegoncharov, I just wanted to make you aware (in case you aren't currently) that this patch makes the helper skip the notes having more than 10 cards while dispersing siblings.

**Comment by wagewarsgetrichdiegoncharov** [comment] 2023-06-04 17:27
Thanks, that makes sense.

**Comment by L-M-Sherlock** [comment] 2023-06-09 12:55
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11706440/fsrs4anki-helper.zip)

I develop a new version of Disperse Siblings. Could you help me test it?

**Comment by wagewarsgetrichdiegoncharov** [comment] 2023-06-09 21:17
Hm, this is probably an issue on my end, but I'm having trouble getting the file to download. It says done, but still has a progress bar. I'll fool around with it and try again in a little bit!

<img width="337" alt="Screen Shot 2023-06-09 at 5 15 45 PM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/119229686/d9cbd8e4-4b75-4dbf-9f8b-243797c4893f">
<img width="322" alt="Screen Shot 2023-06-09 at 5 16 45 PM" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/119229686/24999104-16eb-455f-a45d-14513e051466">

**Comment by L-M-Sherlock** [comment] 2023-06-10 03:47
> Edit: Disregard, the download eventually resolved fine. I loaded the add on in anki and dispersed all siblings, which it did successfully in 100 seconds! And skimming through my browser, it looks like it did disperse notes with many cards very evenly. Screenshot with due dates for a note with many cards below.

Do you prefer this version? I use a new heuristic algorithm to disperse siblings.

@user1823 @Expertium, if you are available, I hope you could test this version.

**Comment by L-M-Sherlock** [comment] 2023-06-10 07:38
<img width="667" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/e28f52e8-a278-4cd2-8f76-c6cee1eb40b8">

I added a progress bar to rescheduling and dispersing.

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11711849/fsrs4anki-helper.zip)

**Comment by Expertium** [comment] 2023-06-10 11:17
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/80c96553-1bc2-435f-a0ce-4b110dedbc98)
The bar is always full. It would be better if it was slowly filling up. Other than that it seems to be working fine.

**Comment by L-M-Sherlock** [comment] 2023-06-10 12:35
> The bar is always full. It would be better if it was slowly filling up. Other than that it seems to be working fine.

Is it inconsistent with the bar of synchronization? I use the same tool.

**Comment by L-M-Sherlock** [comment] 2023-06-10 12:35
> EDIT: shouldn't it be "cards dispersed", not "notes dispersed"?

Because the Helper disperses cards note by note.

**Comment by Expertium** [comment] 2023-06-10 12:38
Oh, you're right. The bar is always full for all other features, too.
I noticed one more thing: pressing the close button doesn't do anything.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/7840e9fe-2a6a-44e9-af5a-cd1838eb9f23)

**Comment by L-M-Sherlock** [comment] 2023-06-10 12:46
> I noticed one more thing: pressing the close button doesn't do anything.

Because I didn't implement the cancellation. Do you need it?

**Comment by Expertium** [comment] 2023-06-10 12:51
I don't _really_ need it, but it's better to have a functioning button than a button that doesn't do what it's supposed to do. It's less confusing and you won't have to worry about some user asking "Why is the button not working?".

**Comment by L-M-Sherlock** [comment] 2023-06-10 12:54
Make sense. I will improve it later.

**Comment by user1823** [comment] 2023-06-10 12:57
I tested this version. It led to some jerky experience during auto-reschedule + auto-disperse, probably caused, in part, due to a small number of cards to reschedule and disperse.

It first showed the "Rescheduling" progress bar. Then, it showed a tooltip saying "{n} cards rescheduled". The tooltip closed quickly and a progress bar for the disperse siblings flashed for a split second on the screen (it lasted for such a small time that I couldn't even see what it was) and then it showed a tooltip saying "{n} cards rescheduled. {x} cards in {y} notes dispersed."

**Comment by L-M-Sherlock** [comment] 2023-06-10 14:45
> I don't _really_ need it, but it's better to have a functioning button than a button that doesn't do what it's supposed to do. It's less confusing and you won't have to worry about some user asking "Why is the button not working?".

It is harder than I thought. I asked Dae the question.

**Comment by L-M-Sherlock** [comment] 2023-06-10 14:54
> I tested this version. It led to some jerky experience during auto-reschedule + auto-disperse, probably caused, in part, due to a small number of cards to reschedule and disperse.
> 
> It first showed the "Rescheduling" progress bar. Then, it showed a tooltip saying "{n} cards rescheduled". The tooltip closed quickly and a progress bar for the disperse siblings flashed for a split second on the screen (it lasted for such a small time that I couldn't even see what it was) and then it showed a tooltip saying "{n} cards rescheduled. {x} cards in {y} notes dispersed."

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11712683/fsrs4anki-helper.zip)
When the number of rescheduled cards are less than 500, it will not show the progress bar. It seems fix the problem.

**Comment by wagewarsgetrichdiegoncharov** [comment] 2023-06-10 21:25
My progress bar is stayed empty for 5 or 10 seconds while it started dispersing siblings, but then I got a 2499/5000 notes dispersed (etc.) dialogue box. I like the addition of the progress bar and dialogue box very much, though! Before I was getting the Mac rainbow spinner and couldn't always tell whether Anki had frozen or it was just still running.

**Comment by user1823** [comment] 2023-06-11 07:20
In my opinion, it is working reasonably well. I will be able to provide further feedback after few more days of testing, but I don't think that you should hold this off until then.

So, unless you want to hold this off until the following issue is solved, you can merge this now.

> > I don't _really_ need it, but it's better to have a functioning button than a button that doesn't do what it's supposed to do. It's less confusing and you won't have to worry about some user asking, "Why is the button not working?".
> 
> It is harder than I thought. I asked Dae the question.

**Comment by user1823** [comment] 2023-06-11 07:25
> Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11712683/fsrs4anki-helper.zip)
> When the number of rescheduled cards are less than 500, it will not show the progress bar. It seems fix the problem.

By the way, I don't think that this patch changed anything. I am still seeing the progress bar even if the number of rescheduled cards is as small as 3 cards.

**Comment by user1823** [comment] 2023-06-11 07:38
Wait, I encountered a major problem. With this version and with auto-reschedule enabled, you can't switch profiles.

When you click switch profile, Anki starts an automatic sync and then goes to the "Profiles" window. Now, the add-on tries to reschedule the cards (because a sync has just been completed) but it can't because the collection has been closed.

This didn't cause much problem earlier. But now, because the helper is trying to reschedule the cards, the progress bar appears and prevents the user from clicking anywhere else.

In my opinion, the best way to solve this issue is to make sure that rescheduling + dispersing is complete before the collection is closed.

**Comment by L-M-Sherlock** [comment] 2023-06-11 08:14
Thanks for your report. I reproduced this bug, but got a different result:

<img width="500" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/57cd7f08-b9ae-458f-8917-b887ec59c3e2">

I need to do more research here.

**Comment by L-M-Sherlock** [comment] 2023-06-11 08:55
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11714218/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/d509da161989fa54508ee13eade3e19e6af76774

I block the main thread until the reschedule is finished. It's not an elegant implementation, but it works for me.

**Comment by user1823** [comment] 2023-06-11 09:07
It works for auto-reschedule. But, I couldn't test it for auto-disperse because I don't have any due cards now. I can test it tomorrow.

**Comment by L-M-Sherlock** [comment] 2023-06-11 09:24
> Oh, you're right. The bar is always full for all other features, too.
> I noticed one more thing: pressing the close button doesn't do anything.

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11714278/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/026413239aa074dce4aaebea874ff655e4a4679b

This patch allows you to stop rescheduling and dispersing.

**Comment by user1823** [comment] 2023-06-12 14:34
> Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11714218/fsrs4anki-helper.zip)
> Commit: [d509da1](https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/d509da161989fa54508ee13eade3e19e6af76774)
> 
> I block the main thread until the reschedule is finished. It's not an elegant implementation, but it works for me.

I tested this again today. I got the following error after I clicked Switch Profile. I think that the problem is with the disperse siblings. You should prevent the collection from closing until dispersing is complete.

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2023-06-12 19:56:41

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "C:\Users\<user>\AppData\Roaming\Anki2\addons21\759844606\reschedule.py", line 105, in on_done
    tooltip(future.result())
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "C:\Users\<user>\AppData\Roaming\Anki2\addons21\759844606\reschedule.py", line 109, in <lambda>
    mw.taskman.run_in_background(lambda: disperse_siblings_backgroud(did, filter, filtered_nid_string, text_from_reschedule=text), on_done)
  File "C:\Users\<user>\AppData\Roaming\Anki2\addons21\759844606\disperse_siblings.py", line 96, in disperse_siblings_backgroud
    best_due_dates = disperse(cards)
  File "C:\Users\<user>\AppData\Roaming\Anki2\addons21\759844606\disperse_siblings.py", line 58, in disperse
    due_ranges_last_due = {cid: get_due_range(cid, did_to_deck_parameters[did], stability) for cid, did, stability in siblings}
  File "C:\Users\<user>\AppData\Roaming\Anki2\addons21\759844606\disperse_siblings.py", line 58, in <dictcomp>
    due_ranges_last_due = {cid: get_due_range(cid, did_to_deck_parameters[did], stability) for cid, did, stability in siblings}
  File "C:\Users\<user>\AppData\Roaming\Anki2\addons21\759844606\disperse_siblings.py", line 40, in get_due_range
    last_due = get_last_review_date(revlogs[0])
  File "C:\Users\<user>\AppData\Roaming\Anki2\addons21\759844606\utils.py", line 200, in get_last_review_date
    return math.ceil((last_revlog.time - mw.col.sched.day_cutoff) / 86400) + mw.col.sched.today
  File "anki.scheduler.base", line 50, in day_cutoff
  File "anki.scheduler.base", line 42, in _timing_today
  File "anki._backend_generated", line 70, in sched_timing_today
  File "anki._backend", line 156, in _run_command
anki.errors.InvalidInput: CollectionNotOpen
```

**Comment by L-M-Sherlock** [comment] 2023-06-12 16:07
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11725458/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/98bb0156e15a68874aa454a938150680ad069c35

This patch would solve the `CollectionNotOpen` error. Maybe it could also solve the progress bar flashing problem.

**Comment by user1823** [comment] 2023-06-12 16:35
> Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11725458/fsrs4anki-helper.zip) Commit: [98bb015](https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/98bb0156e15a68874aa454a938150680ad069c35)
> 
> This patch would solve the `CollectionNotOpen` error. Maybe it could also solve the progress bar flashing problem.

I will test this version tomorrow when I will have more cards to review and reschedule.

By the way, you used https://github.com/hgiesel/anki_straight_reward as the reference for implementing the sync hook. So, it might be a good idea to check how that add-on deals with this problem (auto-sync occurring while closing the collection). Probably, the author of that add-on would have found a better solution.

**Comment by L-M-Sherlock** [comment] 2023-06-12 17:01
> By the way, you used https://github.com/hgiesel/anki_straight_reward as the reference for implementing the sync hook. So, it might be a good idea to check how that add-on deals with this problem

This add-on doesn't run the function in the background, so it doesn't meet our problem. The progress bar requires the background implementation.

**Comment by user1823** [comment] 2023-06-13 14:51
> Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11725458/fsrs4anki-helper.zip)
> Commit: [98bb015](https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/98bb0156e15a68874aa454a938150680ad069c35)
> 
> This patch would solve the `CollectionNotOpen` error. Maybe it could also solve the progress bar flashing problem.

This patch solved the `CollectionNotOpen` error. I didn't see this error after clicking Switch Profile.

However, I also didn't see the "x cards rescheduled." or "x cards in y notes dispersed." tooltips when I clicked the Switch Profile button.

Also, I think that auto-rescheduling took place (without showing the tooltip) after clicking the Switch Profile button, but auto-dispersing didn't, even though I have enabled both.

**Comment by user1823** [comment] 2023-06-13 15:42
> Unless I use pop-ups such as showWarning that require the user to click to confirm to prevent the collection from closing.
> 
> <img alt="image" width="495" src="https://user-images.githubusercontent.com/32575846/245530378-3a007fa2-3036-4220-8d6c-fa87837fd459.png">

I think that this is a good enough solution for now. We can obviously improve it in the future if we get better ideas.

**Comment by L-M-Sherlock** [comment] 2023-06-13 15:53
> If that is the case, I think that a better solution would be to add a delay between the displaying the tooltip and closing of the collection.
> The duration of the delay can be chosen to be the same duration for which any tooltip persists in Anki before it automatically closes.

I have tried it. It doesn't work. The delay would freeze the main window, and the tooltip doesn't appear.

**Comment by user1823** [comment] 2023-06-13 15:59
In that case, the quick solution would be to show that "warning" but only when the collection is being closed (such as on clicking Switch Profile or while closing Anki) and when the number of cards rescheduled is non-zero.

We can find out a better solution later.

**Comment by L-M-Sherlock** [comment] 2023-06-13 16:03
> In that case, the quick solution would be to show that "warning" but only when the collection is being closed (such as on clicking Switch Profile or while closing Anki) and when the number of cards rescheduled is non-zero.

The current framework of Anki doesn't support this complex conditions. The function only knows that the sync ends, and it should be executed. It doesn't know any other things. The function also doesn't know that the sync is manual or auto, happens when collection starts or ends. This why it costs me much time.

**Comment by L-M-Sherlock** [comment] 2023-06-13 16:16
Usually, auto-rescheduling is triggered after syncing from another device. So, in most cases, it happens when the collection starts. Only when you open the collection, do the review in your another device, sync those review logs to Ankiweb and close your collection, the auto-rescheduling will be triggered.

**Comment by user1823** [comment] 2023-06-13 16:19
> Usually, auto-rescheduling is triggered after syncing from another device. So, in most cases, it happens when the collection starts. Only when you open the collection, do the review in your another device, sync those review logs to Ankiweb and close your collection, the auto-rescheduling will be triggered.

Yes, that's why I am not very concerned about this (and say that you can merge this even if you don't get the solution). But, if possible, we should always try to cover all the cases that could be encountered.

**Comment by L-M-Sherlock** [comment] 2023-06-13 16:29
https://forums.ankiweb.net/t/is-it-possible-to-delay-the-closing-of-collection/31204

I asked for help in this post. I will check it tomorrow.

**Comment by L-M-Sherlock** [comment] 2023-06-14 02:17
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/5fdfe59a-86a5-4a60-b8ce-1d265964cfcb)

Someone provide me with a solution. This message box can auto disappear.

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11740879/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/69aec382773cbf71166f2566a5eed254b30455bb

**Closed** 2023-06-14 05:43 UTC
Labels: bug
