### ISSUE TITLE
[BUG] Target undo op not found error

### ISSUE THREAD

**Issue by matejdro** [open-spaced-repetition/fsrs4anki-helper#331] opened 2023-12-23 05:44 UTC
**Describe the bug**

I just got this error while trying to undo while reviewing. Not sure how to reproduce it:

```

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 138, in _on_closures_pending
    closure()
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 82, in <lambda>
    lambda future: self.run_on_main(lambda: on_done(future))
                                            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 102, in wrapped_done
    on_done(fut)
  File "/usr/lib/python3.11/site-packages/aqt/operations/__init__.py", line 127, in wrapped_done
    self._success(result)
  File "/usr/lib/python3.11/site-packages/aqt/reviewer.py", line 434, in after_answer
    self._after_answering(ease)
  File "/usr/lib/python3.11/site-packages/aqt/reviewer.py", line 444, in _after_answering
    gui_hooks.reviewer_did_answer_card(self, self.card, ease)
  File "/usr/lib/python3.11/site-packages/_aqt/hooks.py", line 4173, in __call__
    hook(reviewer, card, ease)
  File "/home/matej/.local/share/Anki2/addons21/759844606/schedule/disperse_siblings.py", line 229, in disperse_siblings_when_review
    mw.col.merge_undo_entries(undo_entry)
  File "/usr/lib/python3.11/site-packages/anki/collection.py", line 1027, in merge_undo_entries
    return self._backend.merge_undo_entries(target)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anki/_backend_generated.py", line 255, in merge_undo_entries
    raw_bytes = self._run_command(3, 11, message.SerializeToString())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anki/_backend.py", line 158, in _run_command
    raise backend_exception_to_pylib(err)
anki.errors.InvalidInput: target undo op not found
```

**Environment**

Anki 23.10.1 (fac9e0ee) Python 3.11.6 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-6.6.7-arch1-1-x86_64-with-glibc2.38

**Additional context**

My config:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/507922/3d0172b7-b744-4bed-8ea2-606911aa1a3b)

**Comment by L-M-Sherlock** [comment] 2023-12-23 08:43
Do you use any other add-ons?

**Comment by L-M-Sherlock** [comment] 2023-12-23 08:45
https://github.com/ankitects/anki/commit/30ae9f7c5408420c8f347073a9e5e62756a6d7cb

It's a bug of Anki. And it will be fixed in 23.12.

**Comment by matejdro** [comment] 2023-12-23 10:23
Here are all my addons:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/507922/c42061ec-c776-47fc-bb2a-680b2c5d34cf)

**Comment by L-M-Sherlock** [comment] 2023-12-23 12:22
I guess it's due to the second add-on.

**Comment by matejdro** [comment] 2023-12-23 18:24
I kinda doubt it, all this addon does is set the ease of the spacebar button. 

[Automatic_Scoring.py.txt](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13759926/Automatic_Scoring.py.txt)

**Comment by L-M-Sherlock** [comment] 2023-12-25 03:41
Could you reproduce this error in Anki 23.12?

**Comment by matejdro** [comment] 2023-12-25 06:28
I can't reproduce it on any version 🤷‍♂️.

**Closed** 2024-01-08 10:44 UTC
Labels: bug
