### ISSUE TITLE
[BUG] Cards of same note show in succession during review

### ISSUE THREAD

**Issue by winklerbua** [open-spaced-repetition/fsrs4anki-helper#205] opened 2023-08-26 04:54 UTC
Issue which was explained here https://www.reddit.com/r/Anki/comments/160r0kj/fsrs_does_show_cards_of_same_note_in_succession_a/

I don't know what else you need? Settings that already are used/tried are "auto disperse siblings after sync and review" "disperse all siblings was done" review order in Anki is set to "due date then random" or "random" etc.
Only thing I don't use is the vanilla Anki function of burying siblings after reviewing one of them since as I explained I don't think it's viable to bury all of them til the next day, I just need it to be randomized so these cards would only show up very close to each other by occasionally by chance.

**Comment by L-M-Sherlock** [comment] 2023-08-26 04:56
Could you provide the card info of those affected cards? I guess their intervals are short, so FSRS doesn't disperse them.

**Comment by winklerbua** [comment] 2023-08-26 08:51
![exa3](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/142659243/15ba5420-449f-47a0-bf79-507f084d4280)
![exa2](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/142659243/7dced6a5-3562-458b-9910-1f372c129b32)

yes so these are the type of cards where this happened today. So the intervals are short, but as I said I don't need or even want "dispersing" in terms of showing them on different days, they should just not show up directly after each other.

**Comment by L-M-Sherlock** [comment] 2023-08-26 08:57
> So the intervals are short, but as I said I don't need or even want "dispersing" in terms of showing them on different days, they should just not show up directly after each other.

But FSRS couldn't control the review sort order. It's the responsibility of Anki's short-term scheduler.

**Comment by winklerbua** [comment] 2023-08-26 09:05
I mean something has to be in there that does this, since when I use the normal algorithm this never happened. It was a big reason why I abandoned the fsrs at some point. These cards are all already at least in their first fsrs step.

**Comment by L-M-Sherlock** [comment] 2023-08-26 09:09
> since when I use the normal algorithm this never happened.

It's weird. If you doesn't use `Bury review siblings`, it would also happen with the normal algorithm.

**Comment by dae** [comment] 2023-08-27 08:01
Are you using the FSRS add-on, and if so, does disabling it seem to make a difference? (of course, leaving FSRS active in your deck settings).

**Comment by winklerbua** [comment] 2023-08-28 06:48
I have disabled the FSRS helper add-on today and after 150 reviews this hasn't happened once now.

**Comment by dae** [comment] 2023-08-28 06:54
Ok, I suspect this is caused by the constant queue rebuilding I mentioned in https://forums.ankiweb.net/t/target-undo-op-not-found/33622/6.

**Comment by L-M-Sherlock** [comment] 2023-08-28 07:07
Do you have any advice? I have not idea how to implement this:

> A more efficient approach would be to do this processing in bulk, when the user is not in the middle of reviews.

**Comment by dae** [comment] 2023-08-28 07:13
For example, your add-on could:

- provide a menu item that looks for reviews scheduled on a weekend, and reschedule any that are
- provide a menu item that searches for the cards answered that day, and reschedules the siblings of cards that were

**Comment by L-M-Sherlock** [comment] 2023-08-28 07:18
Indeed, my add-on has these features. But many users want to automate them. Is it possible to execute the feature when users leave their reviews (e.g., return to main page)?

**Comment by dae** [comment] 2023-08-28 07:34
The most efficient solution (in both CPU time and user convenience) is that such tasks are handled by the Rust backend as cards are reviewed. I do not have any fundamental objections to "skip the weekend" or "load balancing" options, so long as they are implemented in a clean and efficient way (eg not searching through the future reviews on every answer - the information should be cached at queue build time, and updated as cards are reviewed)

For burying, Anki used to bury more than 1 day at a time, and it lead to problems, so I'd like to see a discussion of how those could be avoided/minimized before longer burying times were integrated in the Rust code.

If for now you want to address this in an add-on instead of the Rust core, a hook could be added to the congrats screen and/or or deck list if there isn't one already.

**Comment by L-M-Sherlock** [comment] 2023-08-28 07:42
Yeah, it's efficient to let the Rust backend handle these tasks.

> eg not searching through the future reviews on every answer - the information should be cached at queue build time, and updated as cards are reviewed

Here is my implementation:

1. build a list of count of due cards per day.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/857cba9a70adf62473c07ebc7b8f17f7d416facb/schedule/reschedule.py#L34-L53

2. Find the date with the least count of due cards (exclude free days) in the fuzz range:

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/857cba9a70adf62473c07ebc7b8f17f7d416facb/schedule/reschedule.py#L115-L137

3. update the list of count of due cards per day.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/857cba9a70adf62473c07ebc7b8f17f7d416facb/schedule/reschedule.py#L342-L344

**Comment by winklerbua** [comment] 2023-08-28 07:46
Just to confirm that you guys are fixing the right thing, I did all my like 400 due cards and this didn't happen with the add-on disabled. 
Just so I know, do I now need to enable the add-on and reschedule or what's the solution?

**Comment by L-M-Sherlock** [comment] 2023-08-28 07:47
> For burying, Anki used to bury more than 1 day at a time, and it lead to problems

`Disperse Siblings` in FSRS is more aggressive. It would increase the gap of due among sibling cards as large as possbile (but it would respect their fuzz range).

**Comment by L-M-Sherlock** [comment] 2023-08-28 07:49
> what's the solution?

The immediate solution is disable auto-disperse and auto-reschedule. Or if you want to use auto-disperse, please use it with auto-bury.

**Comment by dae** [comment] 2023-08-28 07:51
Due to time constraints, I'd prefer to focus on the core FSRS integration for now. Once that's done, I'd be happy to discuss/accept  well-written PRs that add this extra functionality.

**Comment by winklerbua** [comment] 2023-08-28 08:25
> > what's the solution?
> 
> The immediate solution is disable auto-disperse and auto-reschedule. Or if you want to use auto-disperse, please use it with auto-bury.

But rescheduling after doing the reviews is fine?

**Comment by L-M-Sherlock** [comment] 2023-08-28 08:30
> But rescheduling after doing the reviews is fine?

Yeah, it's OK.

**Comment by JordanAnthonyKing** [comment] 2023-09-14 08:06
Have these changes been mainlined?
I've been experiencing this issue for quite a while and still often see siblings with wildly different intervals popping up in the same day. It's almost got me convinced that there's some bug in the disperse function that's actively placing these cards on the same day.

**Comment by L-M-Sherlock** [comment] 2023-09-14 08:14
<img width="631" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/5a8480b8-0b44-4db1-a6bf-30cfc51283a0">

Could you enable debug_notify and collect related errors? I need the to solve bug.

**Comment by JordanAnthonyKing** [comment] 2023-09-14 08:21
I'll endeavor to do so during my reviews tomorrow, I wonder if it's related to this:
https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/66
I say this because, in my case, I had several thousand words learned and wanted to add reverse cards to my deck. Instead of attempting to review them all in one day or fiddle with the allowance on my new cards/day, I rescheduled all of these cards to randomly appear within a 3 month range. Since they would therefore have no stats to calculate fuzz from, would the disperser place them right next to their sibling?

**Comment by L-M-Sherlock** [comment] 2023-09-14 08:25
Disperser doesn't affect cards rescheduled manually by users:
- #217

**Comment by JordanAnthonyKing** [comment] 2023-09-14 08:38
Could it instead then be non-manually rescheduled cards not being dispersed around the manually scheduled ones?

**Comment by L-M-Sherlock** [comment] 2023-09-14 08:54
The manually scheduled cards' due and ivl are not modified by the disperse even if they are due in the same day.

**Comment by JordanAnthonyKing** [comment] 2023-09-17 08:16
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/58787893/bf1cd85f-3750-4883-a04e-183ae118fa16)

Card gets dispersed from today into the past, causing it to show up today. I assume this can also happen for future cards. These were both fairly recently learned siblings, no manual rescheduling. Intervals of around a week.

**Comment by JordanAnthonyKing** [comment] 2023-09-17 08:29
A second case of a card being dispersed into the past:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/58787893/ca2cf8c6-f8fc-4aa3-8b14-a3fad8c23f73)

**Comment by JordanAnthonyKing** [comment] 2023-09-17 08:31
Two cards dispersed but still on the same day as eachother:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/58787893/270c3f3e-7842-4247-a1d4-38155e11c679)

**Comment by JordanAnthonyKing** [comment] 2023-09-17 09:02
A card being dispersed so that it ends up closer to its siblings?

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/58787893/c29058de-a189-4d7f-9f56-7012e41c1359)

**Comment by L-M-Sherlock** [comment] 2023-09-18 14:11
@JordanAnthonyKing, could you paste the screenshots of these cards' info?

**Comment by L-M-Sherlock** [comment] 2023-09-18 15:51
> Card gets dispersed from today into the past, causing it to show up today. I assume this can also happen for cards due a few days in the future.

Solved in c2df3ddc49fa6ad4d5723b5d5030400769384ca0

**Comment by JordanAnthonyKing** [comment] 2023-09-19 04:43
> @JordanAnthonyKing, could you paste the screenshots of these cards' info?

How do I view said info?

**Comment by L-M-Sherlock** [comment] 2023-09-19 06:04
<img width="427" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/487cb9a9-8361-4ee1-be9b-55686e7de3d9">

@JordanAnthonyKing, you can view the info in browser.

**Comment by user1823** [comment] 2023-09-19 14:28
@JordanAnthonyKing, do share the info of the affected cards, but also try out the following.

I have pushed a fix that might resolve this issue (at least partially). You can install the patched version of the add-on by downloading the following file, changing the file extension from .zip to .ankiaddon and then opening the file.

[fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12662111/fsrs4anki-helper.zip)

**Comment by JordanAnthonyKing** [comment] 2023-09-20 06:42
Reviewed once, with a high interval, but not being dispersed:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/58787893/dc37c8b9-7960-4d8e-b000-f04561200c3c)

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/58787893/327304dc-1a1b-4eae-a011-7c794d5c60d4)

As far as I can tell from the comment chain this is the only open issue but I will keep an eye out.

**Comment by JordanAnthonyKing** [comment] 2023-09-20 06:48
> @JordanAnthonyKing, do share the info of the affected cards, but also try out the following.
> 
> I have pushed a fix that might resolve this issue (at least partially). You can install the patched version of the add-on by downloading the following file, changing the file extension from .zip to .ankiaddon and then opening the file.
> 
> [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12662111/fsrs4anki-helper.zip)

On the same card as above they now disperse:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/58787893/900e55da-9504-4e15-85c8-46a339cec67d)

**Comment by JordanAnthonyKing** [comment] 2023-10-12 02:42
Hi, just inquiring as to the status of this issue.

I've observed another odd behaviour. I recently increased my desired retention. I didn't reschedule as this would have meant a huge number of reviews, I'm just moving forward with this new retention and seeing how it goes for reviews and new cards.

Having 'Auto disperse siblings' set to true is pulling cards into the present day if I review one of their siblings, and their retention at the current (higher) level would bring their due date into the past/present.

Should there be some sort of parameter to prevent cards being dispersed into the present day, or just moving them into the past in general?

**Comment by L-M-Sherlock** [comment] 2023-10-12 04:52
> Should there be some sort of parameter to prevent cards being dispersed into the present day, or just moving them into the past in general?

I recommend discuss it in this issue:

- #259

**Comment by L-M-Sherlock** [comment] 2023-11-14 10:35
Does the bug still exist after #259?

**Comment by JordanAnthonyKing** [comment] 2023-11-21 07:03
I'm unsure as I've stopped using the feature altogether

**Comment by user1823** [comment] 2024-01-25 10:12
> Having 'Auto disperse siblings' set to true is pulling cards into the present day if I review one of their siblings, and their retention at the current (higher) level would bring their due date into the past/present.

Fixed in https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/350

**Comment by JordanAnthonyKing** [comment] 2024-01-31 02:54
> > Having 'Auto disperse siblings' set to true is pulling cards into the present day if I review one of their siblings, and their retention at the current (higher) level would bring their due date into the past/present.
> 
> Fixed in #350

I'm not sure if the update hasn't been pushed yet or not but I am still seeing this issue

**Comment by user1823** [comment] 2024-01-31 02:57
Did you check for add-on updates in Anki?

**Comment by JordanAnthonyKing** [comment] 2024-01-31 02:59
No updates available

**Comment by user1823** [comment] 2024-01-31 03:00
Are you running Anki 23.10+?

**Comment by JordanAnthonyKing** [comment] 2024-01-31 03:27
Okay, I have the update now, I'll verify tomorrow

**Comment by user1823** [comment] 2024-01-31 03:34
If you updated from 2.1.x to 23.x, I recommend reading [the tutorial for built-in FSRS](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md).

The most important points:
- Enable the built-in FSRS.
- Set the parameters and desired retention in the built-in FSRS. You can copy and paste your old parameters (without the brackets) or you can generate new ones.
- Delete the code in the custom scheduling section.
- Click Save while exiting the Deck Options screen. Otherwise, the changes are discarded and Anki doesn't show any message to let you know.

**Comment by user1823** [comment] 2024-02-06 06:02
@JordanAnthonyKing, was the issue fixed for you?

**Comment by user1823** [comment] 2024-03-11 13:12
I think that this issue can be closed now.

**Closed** 2024-03-11 13:39 UTC
Labels: bug
