### ISSUE TITLE
[Bug] Retention column not displaying the data

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#196] opened 2023-08-20 14:06 UTC
In the browser, the retention column is not displaying the retention of the cards.

<img width="270" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/28d774f2-bf07-41cc-a131-f8c0e5b4ae23">

**Comment by L-M-Sherlock** [comment] 2023-08-20 14:09
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/a93e9305-1df2-4a4b-bc48-9e18ff34343c)

I don't know where `Add-on (retention)` is from. In FSRS, there is retrievability.

**Comment by user1823** [comment] 2023-08-20 14:18
I have disabled all the add-ons except the FSRS helper and restarted Anki. It still shows the `Add-on (retention)` column but not the `Retrievability` column.

**Comment by L-M-Sherlock** [comment] 2023-08-20 14:24
Could you reinstall the FSRS helper add-on?

**Comment by user1823** [comment] 2023-08-20 14:43
I re-installed the add-on but the problem persists.

I also noticed that I get the following columns after uninstalling the helper add-on. This probably suggests that the add-on is unable to create the `Retrievability` column, causing the default `Add-on (retention)` column to appear.

<img width="357" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/b470dd60-4e0d-4adf-b0d6-44aba3a8541d">
<img width="364" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/a35f79e1-6e81-441c-b09f-d1746c049471">

**Comment by user1823** [comment] 2023-08-20 14:52
I solved the problem. The problem was this:
<img width="105" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/cfa9aa49-b2c9-4ec8-8c12-de634d1321ca">

But now, a question arises:
The `Difficulty` and `Stability` columns replace the `Add-on (difficulty)` and `Add-on (stability)` columns respectively. But, why the `Retrievability` column does not replace the `Add-on (retention)` column.

**Comment by L-M-Sherlock** [comment] 2023-08-20 15:37
I have never seen `Add-on (difficulty)` and `Add-on (stability)` in my browser. What's your Anki's version? I need a method to reproduce this bug.

**Comment by user1823** [comment] 2023-08-20 15:52
> I have never seen `Add-on (difficulty)` and `Add-on (stability)` in my browser. What's your Anki's version? I need a method to reproduce this bug.

I am using Anki v2.1.65.

Probably, you will see these columns by right-clicking on the last column in your browser. But, note that the `Add-on (retention)` column disappeared from my Anki after restart. I don't know what is going on here.

<img width="384" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/b4f08221-c23a-4efa-9436-d9c13bb10d37">

**Comment by L-M-Sherlock** [comment] 2023-08-20 15:58
In three week ago, I renamed the column's name from retention to retrievability: 9d89ec0b1d20d639da50f290457e94da72d826d9

Maybe Anki saved the old name?

**Comment by L-M-Sherlock** [comment] 2023-08-20 16:06
It seems a bug of Anki. Because I don't find any column named`retention` in the latest version of FSRS Helper add-on.

**Comment by L-M-Sherlock** [comment] 2023-08-20 16:09
https://github.com/ankitects/anki/blob/70506aeb99d4afbe73321feaf75a2fabaa011d55/qt/aqt/browser/table/model.py#L279-L288

https://github.com/ankitects/anki/blob/70506aeb99d4afbe73321feaf75a2fabaa011d55/qt/aqt/browser/table/model.py#L357-L368

According to these codes, Anki will wrap the column's name with `Add-on ()` when it doesn't exist in `self.columns`.

I guess Anki cached the old name of column.

**Comment by user1823** [comment] 2023-08-20 16:10
I think that Anki is automatically generating the columns from custom data. 

As I said [here](https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/196#issuecomment-1685302447), the columns were visible even when the add-on was deleted and Anki restarted after that.

**Comment by L-M-Sherlock** [comment] 2023-08-20 16:24
I find a way to reproduce the bug.

1. click right-click `difficulty` to enable the column
2. disable FSRS add-on
3. restart Anki
4. you will see Add-on (difficulty) in the browser.

**Comment by dae** [comment] 2023-08-21 03:47
The problem is Anki can't know if you've temporarily disabled/uninstalled an add-on - if it deleted any columns that weren't currently provided by an add-on, the user would lose their settings if they temporarily started Anki with add-ons disabled.

**Comment by L-M-Sherlock** [comment] 2023-08-21 04:18
OK. This problem is not severe. So I close this issue.

**Closed by L-M-Sherlock** 2023-08-21 04:18 UTC
