### ISSUE TITLE
[BUG] A serious and strange bug when rescheduling

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#220] opened 2023-09-08 20:24 UTC
**Describe the bug**
Read these two posts: https://www.reddit.com/r/Anki/comments/16dk35h/fsrs_for_anki_parameter_sanity_check/
https://www.reddit.com/r/Anki/comments/16d56xp/spits_coffee/
They have two opposite problems - abnormally low number of reviews and abnormally high number of reviews. The author of the first post says that not only the Burden is very low, but the actual number of cards to review is very low as well. This means that it's not just a bug with the Burden formula, but a much more serious issue with rescheduling itself.

**To Reproduce**
Unfortunately, it's unclear how to reproduce it.

**Additional Context**
Settings and parameters of the user with an abnormally high Burden:
```
"deckName": "global config for FSRS4Anki",
"w": [0.1358, 0.5044, 18.4034, 18.4034, 4.8368, 1.1219, 0.8531, 0.0, 1.3932, 0.1, 0.8975, 2.0978, 0.1428, 0.3228, 1.3624, 0.2382, 2.7056],
// The above parameters can be optimized via FSRS4Anki optimizer.
// For details about the parameters, please see: https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm
// User's custom parameters for global
"requestRetention": 0.9, // recommended setting: 0.75 ~ 0.95
"maximumInterval": 36500,
```

Settings and parameters of the user with an abnormally low Burden:
```
Parameters: [0.438, 0.7791, 1.0778, 12.3026, 5.8574, 0.6821, 0.8479, 0.0594, 1.2555, 0.1, 0.9616, 2.8513, 0.011, 0.1572, 1.9999, 0.5743, 3.69]
Requested retention: 0.9
Max interval: 36500
```

**Comment by HazemMSaleh** [comment] 2023-09-08 20:37
Hi, I am the user with the abnormally low burden. [Here is a link](https://colab.research.google.com/drive/1V5q2NI-8BnXmG5VrmZXm8IdmiB7JWGbm#scrollTo=NRAsHXATHmZp) to the optimizer output that got parameters described above.

**Comment by Expertium** [comment] 2023-09-08 20:41
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/68c4f7f1-69d8-4f42-b44b-14e9b1db8b35)

**Comment by Expertium** [comment] 2023-09-08 20:41
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/56721bbb-e3b4-461a-a883-32664c6b6b37)

**Comment by HazemMSaleh** [comment] 2023-09-08 20:43
I just changed the permissions so anyone should be able to view it now.

**Comment by Expertium** [comment] 2023-09-08 20:48
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/1e079fc8-9cba-44f1-9637-a52343b45787)
This seems fairly normal. @L-M-Sherlock, I suspect the issue is not with the optimizer, but either with the helper or the scheduler.

**Comment by HazemMSaleh** [comment] 2023-09-08 21:02
Here's my deck. No concerns with you viewing the contents. Github doesn't allow me to upload .apkg files in replies so I've compressed it as a .zip.
[Chinese vocabulary.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12563722/Chinese.vocabulary.zip)

**Comment by L-M-Sherlock** [comment] 2023-09-09 04:37
> Settings and parameters of the user with an abnormally low Burden:

I rescheduled all cards and check the stats:

<img width="774" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/f254144b-f5f7-4003-9442-d79fffbf1187">

<img width="637" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/1d85b6d5-f840-45cd-b3ab-a880c8657516">

Is this burden too low?

**Comment by L-M-Sherlock** [comment] 2023-09-09 07:07
> https://www.reddit.com/r/Anki/comments/16d56xp/spits_coffee/

I have checked the affected deck. I find the user has many cards with interval = 1 day because the user made a batch of manul reset.

<img width="940" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/dadce1cb-a762-4e2c-8290-56961ac73a05">

<img width="762" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/aa0e22e8-46d8-475c-b9d0-c01c4d129945">

It caused the high burden. And FSRS respect the manual reset of user, so rescheduling doesn't affect thess cards.

**Comment by L-M-Sherlock** [comment] 2023-09-09 07:37
> Here's my deck. No concerns with you viewing the contents. Github doesn't allow me to upload .apkg files in replies so I've compressed it as a .zip.

Do you think this interval is too large? 

<img width="1155" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/81795f68-61ed-40f3-9dee-2e346dd7e7ab">

IMO, you press `easy` five times and remember it well. The interval is optimal for your case.

**Comment by Expertium** [comment] 2023-09-09 07:41
> Is this burden too low?

In his post he said his Burden was **3**.

**Comment by L-M-Sherlock** [comment] 2023-09-09 07:44
But I can't reproduce it.

**Comment by Expertium** [comment] 2023-09-09 07:46
@HazemMSaleh can you please record a video where you reschedule all cards and show the stats window?

Also, please share the following info: your Anki version, your FSRS scheduler version (it's in the scheduler code) and your OS.

**Comment by Expertium** [comment] 2023-09-09 12:46
> I have checked the affected deck. I find the user has many cards with interval = 1 day because the user made a batch of manul reset.

@L-M-Sherlock is there a way to sort cards in the browser to find all manually rescheduled ones?

**Comment by L-M-Sherlock** [comment] 2023-09-09 12:52
I don't know. I find those cards with query `is:review -is:learn` and sort them by interval ascend.

**Comment by HazemMSaleh** [comment] 2023-09-09 14:17
@Expertium 

Anki version: Version ⁨2.1.60 (76d88073)⁩
FSRS4Anki v3.20.0 Scheduler Qt6 (Just updated today, it was running yesterday's latest version when I had the issue)
OS: Windows 10
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/76664511/812b53af-c786-4f91-980d-a1637bc1a9e1)
Video of rescheduling: https://streamable.com/acf5u6

![Stats after rescheduling](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/76664511/19d385fa-1825-473a-a9d0-762b2cd05772)

**Comment by user1823** [comment] 2023-09-09 14:38
> FSRS4Anki v3.20.0 Scheduler

This is the problem. You should be using FSRS scheduler version 4.0 or above with the parameters generated using the latest versions of the optimizer. It looks like that you didn't notice the "note" in the optimizer.

<img width="800" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/afbeb973-b8cb-48c1-88e0-eeee338b9429">

Here is the link to the latest version of the scheduler: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_scheduler.js

**Comment by HazemMSaleh** [comment] 2023-09-09 14:40
@user1823 I was actually was just going to reply that I noticed the exact same thing. I assumed since I had updated my FSRS4Anki that the scheduler would update as well, completely forgot that the scheduler had to be separately updated by copying the code. Now that I've rerun it my stats are correct. Thanks everyone for the help!
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/76664511/e4734e7b-771e-4b1c-bf4c-c2af64491381)

**Comment by Expertium** [comment] 2023-09-09 14:42
> I assumed since I had updated my FSRS4Anki that the scheduler would update as well, completely forgot that the scheduler had to be separately updated by copying the code.

Yeah, this is a bit of problem, I agree.
@L-M-Sherlock we should probably close this issue. The second person's problem (1500+ burden) is not a bug, it seems.

**Comment by L-M-Sherlock** [comment] 2023-09-09 15:14
So it's OK to close this issue?

**Comment by Expertium** [comment] 2023-09-09 15:17
If you don't have any advice for the person with 1500+ burden (they don't use github anyway btw), then yes.

**Comment by L-M-Sherlock** [comment] 2023-09-09 15:21
> If you don't have any advice for the person with 1500+ burden (they don't use github anyway btw), then yes.

I have discussed with him in discord. And I answered a series of problems. He accepted my solution.

**Closed by L-M-Sherlock** 2023-09-09 15:21 UTC
Labels: bug
