### ISSUE TITLE
Two minor issues with the message boxes recently implemented in the add-on

### ISSUE THREAD

**Issue by user1823** [open-spaced-repetition/fsrs4anki-helper#128] opened 2023-06-14 17:08 UTC
I tested the latest version of the Helper add-on. It works very well except for the two minor issues I highlight below:
1. Currently, the add-on displays both the message box and the tooltip after rescheduling, both showing the same message. This is not the expected behaviour and I think that you should disable the tooltip. But, don't make any changes until the following issue is solved.
2. For me, the message box is displaying behind the Anki window, which means that the message box is not visible. I happened to notice this (otherwise, I would have been thinking that the message box is not being displayed at all) because I had Anki open in only one-half of my screen and, thus, I was able to see half of the message box. Because you can view the message box, I think that this issue is specific to Windows. Also, I think that this is a bug on Anki's part. But, I don't know how to describe this issue in a way that Anki developers can understand. So, I would request you to report this to the Anki team.

@Expertium, can you confirm whether the second issue exists on your device? I am asking this to you because I think that you use a Windows computer.

**Comment by L-M-Sherlock** [comment] 2023-06-14 17:14
> * Currently, the add-on displays both the message box and the tooltip after rescheduling, both showing the same message. This is not the expected behaviour and I think that you should disable the tooltip. But, don't make any changes until the following issue is solved.

If I disable the tooltip, the manual rescheduling will also be affected.

> 2\. For me, the message box is displaying behind the Anki window, which means that the message box is not visible. I happened to notice this (otherwise, I would have been thinking that the message box is not being displayed at all) because I had Anki open in only one-half of my screen and, thus, I was able to see half of the message box. Because you can view the message box, I think that this issue is specific to Windows. Also, I think that this is a bug on Anki's part. But, I don't know how to describe this issue in a way that Anki developers can understand. So, I would request you to report this to the Anki team.

I can't reproduce it in my device. Could you provide a GIF?

**Comment by user1823** [comment] 2023-06-14 17:35
> If I disable the tooltip, the manual rescheduling will also be affected.

I think all the tooltips (whether it is for auto-rescheduling, manual rescheduling, postpone or advance) should be replaced by message boxes for the sake of consistency.

> I can't reproduce it in my device. Could you provide a GIF?

https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/92206575/4a630693-5021-4eba-9cb7-8336ae95e698

**Comment by Expertium** [comment] 2023-06-14 17:57
Here is how it works for me (I'm using the latest officially released version of the Helper):

https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/917a7601-5716-4207-b7f7-ff4b3b21c4ae

Notice that at the end of the video the window that says "0 cards rescheduled" only appears for around 1/4 of a second.

**Comment by user1823** [comment] 2023-06-14 18:06
I noticed on examining closely that on my device also there is a flash in the foreground which is followed by the message box appearing in the background. I suppose that the flash is the message box itself which closed very quickly and then another message box is appearing in the background.

**Comment by L-M-Sherlock** [comment] 2023-06-15 02:03
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11751982/fsrs4anki-helper.zip)

I try to fix the issue 2. Could you help me test this patch?

**Comment by L-M-Sherlock** [comment] 2023-06-15 12:07
> Has this been pushed to AnkiWeb? Can I test it from there? I am asking this because I see a new update from AnkiWeb.

Yep. I fixed another bug and pushed them both.

**Comment by user1823** [comment] 2023-06-15 12:14
> Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11751982/fsrs4anki-helper.zip)
> 
> I try to fix the issue 2. Could you help me test this patch?

The message box displays correctly for me after this patch.

**Comment by user1823** [comment] 2023-06-15 12:32
By the way, the duration for which the message box persists is much smaller than the duration for which the tooltip persists.

Crude testing using smartphone stopwatch suggests that the message box persists for 1 second and the tooltip persists for 3 seconds.

So, if you want to replace the tooltip with the message box (for all messages), then the duration should be increased to atleast 1.5 seconds.

Also, I don't feel that the message box significantly delays the closing of the collection. So, I would not suggest removing the message box. But, the final decision is in your hands.

**Comment by neznansky** [comment] 2023-06-20 18:33
I reported on the same issue. It seems to me like the better solution would be to remove the pop-up. First, given the technical limitation mentioned by Jarrett Ye on his first response on this here thread. Second, because the pop-up itself has been complained about (#141). Third, because, it seems to me, it is the tooltip that is the more consistent behaviour — Anki already employs tooltips for notifications but not popups.

**Comment by user1823** [comment] 2023-06-21 01:34
The only problem with using tooltips is that tooltips are not shown while closing the collection (unless closure is slightly delayed in another way). This means that you won't be shown the notification when closing the collection (such as when closing Anki or when switching profiles). This was also the reason that the popup was added in the first place.

**Comment by L-M-Sherlock** [comment] 2023-06-22 15:35
> The only problem with using tooltips is that tooltips are not shown while closing the collection (unless closure is slightly delayed in another way). This means that you won't be shown the notification when closing the collection (such as when closing Anki or when switching profiles). This was also the reason that the popup was added in the first place.

I think this info is not important enough to delay the closing of collection. I rarely check the number of rescheduled cards unless I need to debug.

**Closed** 2023-06-23 08:55 UTC
Labels: enhancement
