### ISSUE TITLE
[BUG] Getting "Anki has encountered an unexpected error when closing Anki.

### ISSUE THREAD

**Issue by jonahspear-toast** [open-spaced-repetition/fsrs4anki-helper#400] opened 2024-05-01 19:05 UTC
**Describe the bug**

Getting "Anki has encountered an unexpected error when closing Anki. Anki is saying that it is an issue with fsrs4anki-helper. Here is the debug info:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.3.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "/Users/jspear/Library/Application Support/Anki2/addons21/759844606/schedule/reschedule.py", line 171, in on_done
    mw.reset()
  File "aqt.main", line 851, in reset
  File "aqt.main", line 803, in _synthesize_op_did_execute_from_reset
  File "_aqt.hooks", line 3840, in __call__
  File "aqt.deckchooser", line 120, in on_operation_did_execute
  File "aqt.deckchooser", line 82, in _update_button_label
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Review Bottom Bar ['1136455830', 2024-02-04T13:38, 'None', mod]
FSRS4Anki Helper ['759844606', 2024-04-26T13:38, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
PassFail 2 Remove the Easy and Hard buttons ['876946123', 2023-01-23T20:59, 'None', '']
Progress Bar cards done cards left secondscard time spentleft and ETA ['1097423555', 2023-10-02T04:05, 'None', mod]
Puppy Reinforcement ['1722658993', 2023-11-16T07:59, 'None', '']
Reset Ease ['947935257', 2023-11-11T20:22, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
right hand reviews  hjkl answer shortcuts  Handy Answer Keys configurable ['850294128', 2023-05-24T05:00, 'None', '']

===IDs of active AnkiWeb add-ons===
1097423555 1136455830 1374772155 1722658993 1771074083 759844606 850294128 876946123 947935257

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - Anki version: [e.g. 2.1.55]
 - Scheduler version: [e.g. v1.0.0]
 - Optimizer version: [e.g. v1.0.3]
 - Simulator version: [e.g. v1.1.0]

**Additional context**

**Comment by L-M-Sherlock** [comment] 2024-05-02 01:27
Which feature do you enable in the helper add-on?

**Comment by L-M-Sherlock** [comment] 2024-05-05 10:10
Sorry for this delayed reply. I have come back from my vacation just now. I cannot reproduce your issue. How many times do you meet this error?

**Comment by RichFS-Liao** [comment] 2024-06-02 08:29
I'm not sure if others have encountered the same issue, but I've noticed that when I close Anki, it remains in the background processes. This prevents me from reopening Anki next time, requiring me to manually close Anki from the Task Manager.

I've made several attempts to troubleshoot, and as a conclusion, the error seems to occur during the synchronization process when closing Anki, and it only happens when there's nothing to synchronize.

I've found that commenting out lines 96 and 97 in sync_hook.py can avoid this situation (for testing purposes, not as a solution). This might help in pinpointing the entry point of the problem.

**Comment by L-M-Sherlock** [comment] 2024-06-02 09:26
It's a problem related to Orphan Process. FSRS helper add-on runs rescheduling and dispersing in subprocess of Anki. Sometimes the main process of Anki has been terminated, but the subprocess is still running.

**Comment by danielrk** [comment] 2024-06-04 14:53
I believe I have the same issue as @RichFS-Liao. I can't quit MacOS Anki Version ⁨24.04.1 when I have the FSRS helper add-on enabled (the window will close, but Anki is still running) and it requires force quit. These are the settings I have:

<img width="432" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/2603626/31a6cf86-f93a-4571-803b-b84e3a5b6c64">

@L-M-Sherlock - can you clarify whether this orphan process issue is a bug with the add-on, or Anki?

**Comment by L-M-Sherlock** [comment] 2024-08-12 02:24
fixed by https://github.com/ankitects/anki/issues/3190

**Closed by L-M-Sherlock** 2024-08-12 02:24 UTC
Labels: bug
