### ISSUE TITLE
[Feature Request] Change "Disperse Siblings" so that it cannot increase the number of cards due today

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#259] opened 2023-10-07 14:56 UTC
**Which module is related to your feature request?**
Scheduler and Helper.

**Is your feature request related to a problem? Please describe.**
Right now using Disperse Siblings can increase the number of cards due today. This is unintuitive (when people see the word "disperse" they assume it will _decrease_ the number of reviews) and discourages people from using this feature.

**Describe the solution you'd like**
Suppose there are 2 cards that are siblings. There are 3 possible scenarios:
1) Both of them are due later, not today. In that case, dispersing either of them should not affect the number of cards due today.
2) One of them is due today, the second is due later. In that case, the interval of one of them needs to increase, which, again, shouldn't increase how many cards are due today. If the first card is postponed, the number of cards due today will decrease by 1. If the second card is postponed, the number of cards due today shouldn't change.
3) Both of them are due today. In this case, one of them should be dispersed, therefore decreasing the number of due cards today by 1.

**Additional context**
I'm using the latest version of the Helper and 23.10beta4.

**Comment by user1823** [comment] 2023-10-08 05:00
> Both of them are due later, not today. In that case, dispersing either of them should not affect the number of cards due today.

What if both of them are due on the same day (or close to each other)? In this case, one (or both) of the cards needs to be dispersed. What if the maximum distance is achieved by scheduling one of the cards today?

Here is the relevant code that decides which dates the function can access while dispersing the siblings.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c5cad0017f93858498831ea97442b750708371ac/schedule/disperse_siblings.py#L78-L85

Do you have any specific suggestions for the code?

**Comment by Expertium** [comment] 2023-10-09 19:16
> What if both of them are due on the same day (or close to each other)? In this case, one (or both) of the cards needs to be dispersed. What if the maximum distance is achieved by scheduling one of the cards today?

The interval of one of those cards should become longer. The key idea is to ensure that Disperse Siblings **cannot make intervals shorter**. @L-M-Sherlock, I don't know how exactly to implement it, but I hope you agree with what I said. If Disperse Siblings can make intervals of cards shorter, it can result in the number of due cards increasing after using this feature, which is undesirable, as it confuses users and gives them more work.

**Comment by L-M-Sherlock** [comment] 2023-10-10 01:41
> The key idea is to ensure that Disperse Siblings **cannot make intervals shorter**.

But it would also make the retention lower and lower.

**Comment by Expertium** [comment] 2023-10-10 08:42
Siblings have higher retention than necessary if shown right after each other, so it's fine.

**Comment by L-M-Sherlock** [comment] 2023-10-14 12:41
Here is a tricky case: https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/205#issuecomment-1758825196

To ensure the interval is in the range of fuzz, `disperse siblings` will re-calculate the interval based on the stability and requestRetention. If the user increase the requestRetention, `disperse siblings` will shorten the interval inevitably.

**Comment by Expertium** [comment] 2023-10-14 12:46
I suppose that can't be helped. But I still think that when requested retention doesn't change, dispersing siblings shouldn't increase the number of due cards.

**Comment by user1823** [comment] 2023-10-14 14:32
In my opinion, you are suggesting to make this feature work like the Delay Siblings add-on. The problems with that approach include:

1. We don't understand how the review of a sibling affects the retrievability of the other one. So, we can't accurately know how much should the sibling should be delayed.
2. If one of the siblings is being reviewed frequently at short intervals, the other card will get delayed multiple times. This might cause its retrievability to fall significantly.

The disperse siblings feature solves both of these problems by using the fuzz range to disperse the siblings.

Now, to maximize the gap between the siblings, it is essential to allow the function to utilise all the possible dates.

If we don't allow the card's interval to decrease, the siblings can't be dispersed if the cards are currently scheduled near the end of their fuzz range.

By the way, here are the differences between Delay Siblings and Disperse Siblings: https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/80#issuecomment-1521635863

**Comment by Expertium** [comment] 2023-10-26 18:45
I just experienced the following: I have a card that is in the "review" stage, and it has a "new" sibling. I reviewed the "new" sibling, and the other card, the one in the "review" stage, appeared as due.
![Disperse Siblings not working as intended (compressed)](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/1b957d2f-5589-408d-9756-c60ea724ae90)
(I have zoomed in on the bottom part to make it easier to see)
**This is the exact opposite of what dispersing siblings should achieve**. Instead of setting the siblings further apart, it brought them closer together.
@L-M-Sherlock I highly recommend you to change how code works to ensure that intervals cannot be shortened.

**Comment by L-M-Sherlock** [comment] 2023-10-27 02:20
> I highly recommend you to change how code works to ensure that intervals cannot be shortened.

I have provided many reason why I don't change the code to ensure that intervals cannot be shortened.

For your case, the add-on has considered the latest_review_date and the due_range of your two cards. The second cards should be dispersed to the date between today and the due date of the first card. If not, it could be caused by the due range doesn't allow its interval to increase. If so, you proposed method couldn't solve this problem.

**Comment by Expertium** [comment] 2023-10-27 09:58
So if you're not planning to change how Disperse Siblings works, should I close this issue?

**Comment by L-M-Sherlock** [comment] 2023-10-27 10:56
If you have a solution to answer the question proposed in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/259#issuecomment-1762944810, I will implement it.

**Comment by Expertium** [comment] 2023-10-27 13:23
A formula for dispersing siblings must satisfy 2 properties:
1) The intervals of any sibling cannot become shorter than before. It can lead to what I reported earlier: both siblings appearing on the same day, or at least very close to each other. Intervals of siblings can either stay the same or increase.
2) Intervals cannot increase indefinitely if one of the siblings is being reviewed frequently. If sibling 1 has a short interval and sibling 2 has a long interval, it's possible that sibling 1 will be reviewed many times before sibling 2, and so sibling 2 will be postponed each time.
I don't know how to satisfy both without using a tagging system that tags cards when they get dispersed, and once a sibling is tagged, it cannot be dispersed again until reviewed. So if sibling 1 was reviewed and sibling 2 was dispersed, reviewing sibling 1 for the second time won't disperse sibling 2 anymore until sibling 2 gets reviewed. If you are fine with that, that would be great. I don't know if it's possible to satisfy both properties using only math without tagging.

**Comment by user1823** [comment] 2023-10-27 14:13
> The intervals of any sibling cannot become shorter than before. It can lead to what I reported earlier: both siblings appearing on the same day, or at least very close to each other.

I suspect that you are referring to [this problem](https://github.com/open-spaced-repetition/fsrs4anki/issues/188#issuecomment-1510018191). But, this problem doesn't exist in disperse_siblings from the very beginning because I highlighted it during the early stages of development. The solution is described in detail in the very next comment.

**Comment by Expertium** [comment] 2023-10-27 14:16
@user1823 I don't know if you saw it or not, but I literally had a siblign appear on the same day after dispersion.
https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/259#issuecomment-1781687399

**Comment by user1823** [comment] 2023-10-27 14:38
Can you share the due dates and intervals of the cards before and after dispersing? (If you don't have them now, you can share these if you see this issue happening again.)

@L-M-Sherlock, I suspect that the observation has something to do with the code for **maximizing the gap between the due dates**, rather than the code for calculating the ranges.

Even if it doesn't turn out to be an error in the code, we can probably add a small check to prevent such issues from occuring.

**Comment by Expertium** [comment] 2023-10-27 14:50
Hopefully this helps
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/0935e1d3-26c6-48ef-986e-840475b5e4e3)

**Comment by user1823** [comment] 2023-10-27 15:04
> I tested it, and desired retention affects whether the sibling will appear today or not after dispersion.

You likely didn't reschedule the cards after changing the desired retention. So, the "pending" change in interval happened when dispersing.

> make it so that siblings are always at least 1 day apart from each other. That way, even if the intervals shorten, at least siblings won't appear on the same day.

Yes, we can do this.

**Comment by L-M-Sherlock** [comment] 2023-10-27 15:31
> code for maximizing the gap between the due dates, rather than the code for calculating the ranges.

Maybe. The code for maximizing the gap uses random sampling to disperse the siblings. So it doesn't ensure the gaps are 100% maximized.

**Comment by Expertium** [comment] 2023-10-27 15:44
@L-M-Sherlock unless you or user1823 have any better ideas, I suggest changing the code to ensure that siblings are always at least 1 day apart from each other, without changing anything else.

**Comment by L-M-Sherlock** [comment] 2023-10-27 16:05
OK. But I have to re-read the code of `Disperse Siblings`. It has been modified by multiple times and people. Maybe it is a chance to refactor the code of `Disperse Siblings`. @user1823, could write a document for `Disperse Siblings`? Here is the page link: https://github.com/open-spaced-repetition/fsrs4anki-helper/wiki/Disperse-Siblings

**Comment by user1823** [comment] 2023-10-27 16:56
> @user1823, could write a document for Disperse Siblings?

I am slightly busy in the next 2-3 weeks. It would be great if you or Expertium can prepare an initial draft of the document, which I can edit.

**Comment by Expertium** [comment] 2023-10-27 17:05
I don't have a very good understanding of the code of Disperse Siblings.

**Comment by user1823** [comment] 2023-10-28 07:53
I took out some time and created a draft with some help from Windows Copilot.

@L-M-Sherlock, please edit the page as you re-read the code of Disperse Siblings.

**Comment by Expertium** [comment] 2023-10-28 08:06
Unrelated to the current issue, but this page should be updated and expanded too. Right now it says practically nothing.
https://github.com/open-spaced-repetition/fsrs4anki-helper/wiki/Load-Balance-&-No-Anki

**Comment by L-M-Sherlock** [comment] 2023-10-28 11:07
> I suggest changing the code to ensure that siblings are always at least 1 day apart from each other, without changing anythin

What if the intervals of siblings are shorter than 2 days and their due dates are the same?

**Comment by Expertium** [comment] 2023-10-28 11:09
Then when sibling 1 is reviewed, sibling 2 is postponed by 1 day.

**Comment by L-M-Sherlock** [comment] 2023-10-28 12:02
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13195690/fsrs4anki-helper.zip)

I refactor the disperse siblings. Now it will pop a message when the min gap is 0 day. The message includes the card id and dispersing range. It will help us improve the feature. @Expertium, could you help me test it?

**Comment by Expertium** [comment] 2023-10-28 12:06
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (7428ecad) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-27 21:14:05
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 138, in _on_closures_pending
  File "aqt.taskman", line 82, in <lambda>
  File "aqt.taskman", line 102, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 434, in after_answer
  File "aqt.reviewer", line 444, in _after_answering
  File "_aqt.hooks", line 4173, in __call__
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 231, in disperse_siblings_when_review
    tooltip("Due dates are too close to disperse: ", str(due_ranges))
  File "aqt.utils", line 971, in tooltip
  File "aqt.progress", line 80, in timer
TypeError: arguments did not match any overloaded call:
  start(self, msec: int): argument 1 has unexpected type 'str'
  start(self): too many arguments

**Comment by L-M-Sherlock** [comment] 2023-10-28 12:11
My fault. Here is the fixed patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13195716/fsrs4anki-helper.zip)

**Comment by Expertium** [comment] 2023-10-28 12:13
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/ce28fea1-2ad6-4f9a-aa31-08791d2ef6fe)
And it still results in the same behavior as [here.](https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/259#issuecomment-1781687399)

**Comment by L-M-Sherlock** [comment] 2023-10-28 12:20
It looks like the problem is in the due range. The due range of  card 1527366857389 is (today, today).

**Comment by L-M-Sherlock** [comment] 2023-10-28 12:23
What's the due range of card 1527366857389 if you just reschedule it?

**Comment by Expertium** [comment] 2023-10-28 12:24
How can I find out the due range?

**Comment by L-M-Sherlock** [comment] 2023-10-28 12:26
The due range should be (last review date + interval * 0.95,last review date + interval * 1.05). The interval is based on the stability and desired retention.

**Comment by Expertium** [comment] 2023-10-28 12:27
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/e079cb4c-fb7f-4101-b37f-6c6ab80963bb)
However, I have recently changed my desired retention without rescheduling all cards.

**Comment by L-M-Sherlock** [comment] 2023-10-28 12:29
Disperse siblings will recalculate the interval based on your current desired retention.

**Comment by Expertium** [comment] 2023-10-28 12:37
Yes, I know, but I want it to also ensure that siblings won't appear on the same day anyway.

**Comment by L-M-Sherlock** [comment] 2023-10-28 12:49
OK. I get it. Maybe we need to loosen the due range before `maximize_siblings_due_gap`.

**Comment by L-M-Sherlock** [comment] 2023-10-28 13:05
I find that it's really hard. Do you accept to add 1 day for all due ranges' left endpoint?

**Comment by L-M-Sherlock** [comment] 2023-10-28 13:08
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13195848/fsrs4anki-helper.zip)

**Comment by Expertium** [comment] 2023-10-28 13:09
> Do you accept to add 1 day for all due ranges' left endpoint?

I guess so.

**Comment by Expertium** [comment] 2023-10-28 13:14
> Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13195848/fsrs4anki-helper.zip)

Nope, still the same issue. Afetr reviewing the "new" sibling, "review" sibling is scheduled to today.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/36da8a24-d274-4a96-a24d-6b8aa26624b2)

**Comment by user1823** [comment] 2023-10-28 13:21
> I find that it's really hard. Do you accept to add 1 day for all due ranges' left endpoint?

Instead of doing this, I think that you can add 1 to the due of all the siblings except one after line 231.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/5af61c3145bf6493a312cfca2f074ced5ff3b5c1/schedule/disperse_siblings.py#L230-L242

**Comment by L-M-Sherlock** [comment] 2023-10-28 13:26
> Instead of doing this, I think that you can add 1 to the due of all the siblings except one after line 231.

But it will still toggle the tooltip.

**Comment by user1823** [comment] 2023-10-28 13:29
> > Instead of doing this, I think that you can add 1 to the due of all the siblings except one after line 231.
> 
> But it will still toggle the tooltip.

It still makes sense to show that there cards have due dates too close to disperse. By the way, I think that this tooltip should be disabled by default.

**Comment by Expertium** [comment] 2023-10-28 13:30
> I think that this tooltip should be disabled by default.

For now let's keep it, for testing purposes. In the official update it should, of course, be disabled.

**Comment by L-M-Sherlock** [comment] 2023-10-28 13:32
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13195883/fsrs4anki-helper.zip)

**Comment by Expertium** [comment] 2023-10-28 13:34
Yes, thank you!
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/3144985a-b105-43ed-b535-a39cf862caa2)
The sibling did not appear this time.

**Comment by L-M-Sherlock** [comment] 2023-10-28 13:36
OK. Closed by a674d89dd4cf92167e19a50891db6c4834f1478e.

**Closed by L-M-Sherlock** 2023-10-28 13:36 UTC
Labels: enhancement
