### ISSUE TITLE
[BUG] Cannot undo rescheduling

### ISSUE THREAD

**Issue by topherbuckley** [open-spaced-repetition/fsrs4anki-helper#172] opened 2023-07-23 17:27 UTC
**Describe the bug**
When using the **FSRS4Anki Helper --> Reschedule All Cards** followed by **FSRS4Anki Helper --> Undo rescheduling in all cards** my collection is still vastly different from where it started. 

**To Reproduce**
1. Open collection in Anki desktop (Ubuntu 22.04)
2. Open Stats and show full collection for 1 year and include backlog. 
3. Print to pdf
4. **FSRS4Anki Helper --> Reschedule All Cards** 
5. repeat steps 2-3
6. **FSRS4Anki Helper --> Undo rescheduling in all cards** 
7. repeat steps 2-3

**Expected behavior**
I would expect the undo rescheduling to bring my collection and scheduling back to where it was prior to rescheduling. 

**Screenshots**
From left to right. Step 3, Step 5, Step 7 from list of steps above. 
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/15166572/b6901a03-c012-4bca-9661-27d88c4ea222)

**Environment**
 - Anki version: 2.1.65 (82caffec)⁩
   Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
 - OS: Ubuntu 22.04
 - Scheduler version: Not sure where to find all three off these individually, but I'm using everything from tag: v4.3.2 on this repo
 - Optimizer version: Installed from pip and also reads 4.3.2 according to `pip list`
 - Simulator version: Don't think I'm using this but correct me if I'm wrong.

**Comment by L-M-Sherlock** [comment] 2023-07-29 10:27
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/5cda9871-2cfc-4109-bc63-6a8ff28ebbd7)

Could you help me check this card? You can search it with query `cid:1587284725830`. I don't know why its due is 2024-07-21 before rescheduling.

**Comment by L-M-Sherlock** [comment] 2023-07-29 10:28
By the way, you can undo rescheduling with `Ctrl + Z`:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/db3f1b39-0a37-433e-b3e8-287714dbe0be)

**Comment by topherbuckley** [comment] 2023-07-30 18:11
> Could you help me check this card? You can search it with query `cid:1587284725830`. I don't know why its due is 2024-07-21 before rescheduling. Its interval is also inconsistent with the interval in the review log.

I honestly don't know. A question for Dae perhaps? I've seen a lot of oddities like this lately, which is why I started looking at alternative schedulers like yours.

**Comment by topherbuckley** [comment] 2023-07-30 18:13
Could this be caused by "bury" perhaps? I have way too many cards to remember if I used it on this one, and I rarely use bury, but I suppose it is a possibility.

**Comment by topherbuckley** [comment] 2023-07-30 18:25
Playing around with bury, it doesn't look like that it seems. I'm recalling there was a phase where I was manually rescheduling a lot of cards in this deck as they were too elementary at the beginning of the deck. As AnkiDroid only allowed me to set the Easy interval to 3.3 months, I manually moved a bunch a few years down the schedule. Not sure why I would have chosen [1258 days](https://www.timeanddate.com/date/durationresult.html?m1=02&d1=09&y1=2021&m2=07&d2=21&y2=2024) but I recall some limit (4 digits right now) to the maximum reschedule time. This seems more likely to be what happened.

**Comment by topherbuckley** [comment] 2023-07-30 18:35
Guessing your code only takes into account the 3.27 months interval and on the Due date? Yeah, I guess you have to have some way to account for manual rescheduling.

**Comment by L-M-Sherlock** [comment] 2023-07-31 01:40
> Guessing your code only takes into account the 3.27 months interval and on the Due date? Yeah, I guess you have to have some way to account for manual rescheduling.

The `undo reschedulings in all card` assume the `3.27` months is calculated by the built-in algorithm, because rescheduling  doesn't modify the `3.27` months. For `manual rescheduling`, there should be manual review log in the revlogs. But in your case, it doesn't exist. So the `undo reschedulings in all card` feature couldn't work as expected.

**Comment by L-M-Sherlock** [comment] 2023-07-31 01:41
> Easy interval to 3.3 months, I manually moved a bunch a few years down the schedule.

How did you do that? Modify the database directly?

**Comment by topherbuckley** [comment] 2023-07-31 02:33
> there should be manual review log in the revlogs.

Where would that normally be? I've never seen such a log. 

> How did you do that? Modify the database directly?
No no, just a menu option in AnkiDroid. See [the docs](http://docs.ankidroid.org/) and search for Reschedule. Not sure if you use AnkiDroid or not, but the desktop Anki appears to have a similar functionality, but under a different name. When reviewing, you can go to the bottom right "More" menu and use "Set Due Date...".

**Comment by topherbuckley** [comment] 2023-07-31 02:35
In the card browser in Anki desktop, there is the same functionality exposed on a right click of any card.

**Comment by L-M-Sherlock** [comment] 2023-07-31 02:40
<img width="394" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/a8f9f3bb-3e84-4a13-84dc-6aca2ecf8a4a">

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/f8d6a46c-f46e-4518-a7c3-ff752c536ebe)

I use the "Set Due Date..." and it has record logs. Maybe in the AnkiDroid this feature has different behaviors?

**Comment by L-M-Sherlock** [comment] 2023-08-10 11:02
I found that your collection have 826 cards whose intervals are longer than the intervals recorded in review logs. When you use `undo reschedulings in all cards`, these cards' intervals are replaced with the values stored in review logs.

```SQL
SELECT COUNT(*)
FROM
(SELECT r.id, r.cid, r.ivl AS revlog_ivl, c.ivl AS card_ivl
FROM (
  SELECT rl1.id, rl1.cid, rl1.ivl
  FROM revlog rl1
  JOIN (
    SELECT cid, MAX(id) AS max_id
    FROM revlog
    GROUP BY cid
  ) rl2 ON rl1.cid = rl2.cid AND rl1.id = rl2.max_id
) r
JOIN cards c ON r.cid = c.id
WHERE c.type = 2)
WHERE card_ivl > revlog_ivl
;
```

So I think it is not a bug of FSRS. I will close this issue.

**Closed by L-M-Sherlock** 2023-08-10 11:02 UTC
Labels: bug
